### ISSUE TITLE
It is unclear what an "off week" is

### ISSUE THREAD

**Issue by BamBalaam** [davebs/AgileLite#10]
It is not super clear what an "off week" is. Do you mean totally off? Or something more along the lines of "people work in lighter tasks such as documentation, contributing to open-source projects, and others"?

**Comment by davebs** [comment]
I added an FAQ that hopefully addresses this question and some others. Excuse the dry humor.

> So you're telling me that engineers get 12 weeks off per year to surf and paint? How would that ever work in a world where 996 is becoming the norm?

I think your team should take as much time off as it's comfortable with.

I will point out that the 40 hour work week was once considered a radical idea. Google started 80% time, we're at 75% time here, I'd like to get that down to 10% time (the Ferris method) by the end of the 2020s.

996 (9am-9pm 6 days per week) is working on the other side of that, seeking to extend the 40 hour work week to a 72 hour work week. I see this as a regression and think people should stop fetishizing long hours. It's not actually more productive.

It's also up to you whether the "week off" is a week for vacation or for a lighter work load or for whatever else. The answer might depend on the particular week. 

Maybe "light week" is easier for people to stomach than "week off". Use whichever you're more comfortable with.

Surfing and painting are in no way required, they were merely cited as examples. In fact, I don't even surf OR paint.
