### ISSUE TITLE
Why a week planning for a 3 week sprint?

### ISSUE THREAD

**Issue by meilhard** [davebs/AgileLite#13]
Do you really think you would need a whole week to decide on which tickets should be in the next sprint? And why shouldn't be the developers included in that process? Don't you think you would need the feedback of the developers to plan a sprint properly?

I generally doubt that this approach is less timeconsuming then regular backlog refinement sessions with the team.

**Comment by davebs** [comment]
Added an FAQ that addresses your questions and some others.

> Are developers included in sprint planning?

Yes. They are not banned from the meeting. They just don't need to attend, especially if they've kept the Issue Tracking System current and the team has discussed some of the items for the next sprint during the course of the previous sprint. 

I'm all for less meetings. Are you a rare person that enjoys meetings? As long as I don't have to attend, don't let me stop you.

> Does it really take a week to plan a sprint?

No, that's the point. It's a light week.
