### ISSUE TITLE
Waterfall?

### ISSUE THREAD

**Issue by meilhard** [davebs/AgileLite#15]
The whole approach really sounds more to me like a waterfall workflow. I am pretty much convinced that you can avoid burnouts by implementing existing agile workflows in the right way.

**Comment by davebs** [comment]
That's interesting, can you be more specific about the connection to waterfall?

> by implementing existing agile workflows in the right way

Unfortunately the only thing consistent about agile is that everyone is doing it wrong.

**Comment by meilhard** [comment]
Yes, you are right unfortunately. And I apologize. My comments weren't really constructive. I just missed some aspects that I find very important in working agile. Like having Stand Ups for example. Having the opportunity once a day to quickly sync on the teams process and probably finding support in more difficult tasks I find very helpful. Or even more important having Retrospectives on a regular basis. I mean how else do you want to reflect on your work and find improvements? 

I also didn't quite understand the idea behind this planning week. You say that the developers don't need to attend. But how else do you want to plan a reasonable sprint? Unless it is the classical way of letting others dictate of what has to be done! I think the team is a crucial part in sprint planning. They will need to decide on how much they can work on, right?

Regarding useless meetings I totally agree with you. I also hate participating in meetings without clear agenda or expected outcome. That is basically why you have only a few very clear defined rituals in scrum for example. Planning, Grooming, Retrospective and Stand Up. That is basically it.

In principal I still believe that if you are doing it right, the existing frameworks are doing a pretty good job in avoiding burnouts. Not without reason they were developed by developers. If that isn't the case you really should improve on the implemented workflow because there is clearly something going wrong but no need for another framework in my opinion.

**Comment by davebs** [comment]
> You say that the developers don't need to attend. But how else do you want to plan a reasonable sprint? Unless it is the classical way of letting others dictate of what has to be done!

Yeah, maybe I'll expand on this at some point, it seems like many people are confused.

> no need for another framework in my opinion.

That's fine, I disagree.
