### ISSUE TITLE
Months are not 4 weeks long

### ISSUE THREAD

**Issue by jeremytubbs** [davebs/AgileLite#17]
There are 52 weeks in a year not 48.

From your faq:

```
> Why 3 week sprints?

Because development work plus recovery time then fits into 12 slots per year. 
```

**Comment by Eguthrie3214** [comment]
I think he mis-typed because you can fit 13 cycles per year.

**Comment by davebs** [comment]
Good catch, updated 12 to 13 and changed the concept of months to cycles. 13 4 week cycles in a 52 week year. Extra day off on leap years.
