### ISSUE TITLE
Change sprint to iteration

### ISSUE THREAD

**Issue by RandomSort** [davebs/AgileLite#23]
Hi, 
awesome project :)

I was thinking that it might be better to change the name sprint to iteration as that gives even more focus on the "without the burnout". It is not a hectic sprint, it is simply an iteration.

Cheers,
Johan

**Comment by davebs** [comment]
Thanks Johan! It's certainly not illegal to call it an iteration, but I personally prefer the term sprint. I tend to work in concentrated bursts with lots of breaks and think "sprint" describes my particular workstyle pretty well. But like I say, it's absolutely ok to pick and choose the elements that work for you--if any system is getting in the way of you doing work, then it's a bad system and should be adjusted for fit.
