### ISSUE TITLE
Has this been actually tried in any existing product/team or this is just a vague idea of how this could possibly work?

### ISSUE THREAD

**Issue by vrch** [davebs/AgileLite#24]
If so, could you show these examples and elaborate a bit on the results (if possible with comparison to the "overcomplicated" agile), as we're actually considering implementation of it as a workflow for a team working on one of the products?

**Comment by davebs** [comment]
There are no case studies but I would like to create some. I'm glad to hear you're thinking about implementing it and would love to hear more about why you're looking at it/how you see it working (or not working) in your organization.

I've been using a similar system on software projects that I manage for several years. The "Agile Lite" documents are the first time I've formalized it, although I'd often described it as "agile lite" in conversations with people and have had a lot of discussions generally about the benefits or lack thereof of different methodologies for organizing work in teams.

I was going to start a list of companies using agile lite and put it in the github repo. Also need to do a "tools" document that lists some opinions about good tools to use for implementing agile lite. But do feel free to reach out to me directly at dave.brian.sullivan@gmail.com if you want to discuss your particular use case.
