### ISSUE TITLE
How would this ever work?

### ISSUE THREAD

**Issue by orangecoding** [davebs/AgileLite#3]
Sorry to throw this in here, but I have to....

To me this reads like a typical "I'm a conference speaker and tell you how to work without getting stressed". Reading this, I was asking myself whether you have actually ever worked in a real company. Sorry, I do not want to sound harsh here, but honestly, having a 3 week sprint without any issues/bugtickets that can be created? How would this ever be possible? 

It's software. Software is broken by nature and if there're no bugs, it means you are not progressing. So if you disallow creating bugtickets/issues and therefor force ppl to wait for fixes for 3 weeks (worst case) you probably don't have much customers anymore after a few of your sprints. Even Kanban has "silver bullets".

I like the fact tho to avoid sidetracks, but there are some very big differences between what you wrote here and what is actually realistic. 

Again, this is completely my own opinion and neither reflects my employer's nor anyone else's opinion :D

**Comment by davebs** [comment]
> So if you disallow creating bugtickets/issues...

On the front page:

> Support work is done on a rotating basis because sometimes things do happen unexpectedly and need to be dealt with, but a surprising number of issues can wait until later.

**Comment by orangecoding** [comment]
lol. This answer was kind of expected 🤣

**Comment by davebs** [comment]
Yeah, it's cool, I overreacted. Edited for brevity.
