### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by davebs** [davebs/AgileLite#6]
People have mentioned that calling this project "Agile Lite" is an affront to the original intent of Agile. Is that true yes/no? And if so, what's a better name?

**Comment by msde** [comment]
AgileLite seems very derivative of Agile-ish development, and maybe should acknowledge more of the history of the building blocks that came before it.

**Comment by SupremeLordCommander** [comment]
What about "SoEasyYourMomCanDoIt"?

**Comment by meilhard** [comment]
Name it after what it actually is: "Waterfall 2.0"

**Comment by davebs** [comment]
Of these I still like Agile Lite best, sticking with that.
